services:
  - type: web
    name: java-openhab-rest-client-backend
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/java-openhab-rest-client-backend-1.0.0.jar
    envVars:
      - key: PORT
        value: 8080
    plan: free
